//
//  PostModel.swift
//  pocketQXassist
//
//  Created by Aleksandr Ataev on 17.01.2024.
//

import Foundation
import SwiftUI

struct PostModel: Identifiable {
    var id = UUID()
    let link: String
    let postImage: String
    let title: String
    let subTitle: String
    let author: String
    let commentImage: String
    let commentsCount: Int
    let rocketImage: String
    let rocketsCount: Int

    static var posts: [PostModel] = [
        PostModel(link: "https://www.tradingview.com/chart/GBPUSD/RlyHMVZe-Sell-GBPUSD-Channel-Breakout/",
                  postImage: "Post1",
                  title: "Sell GBPUSD Channel Breakout",
                  subTitle: "Weaker inflation, higher unemployment and gloom from policymakers. The fall in inflation is not the only issue holding the BoE back from hikes.",
                  author: "KABHI_FOREX_TRADING",
                  commentImage: "commentImage",
                  commentsCount: 30,
                  rocketImage: "rocketImage",
                  rocketsCount: 102),
        PostModel(link: "https://www.tradingview.com/chart/USDJPY/B9wp69AV-USDJPY-Short-after-the-bullrun-with-target-140/",
                  postImage: "Post2",
                  title: "USDJPY | Short after the bullrun with target 140!",
                  subTitle: "The recovery of the US dollar is accelerating as market sentiment fades. The Yen is on the defensive with the hope that the BoJ will keep its extremely accommodative policy unchanged.",
                  author: "Forex48_TradingAcademy",
                  commentImage: "commentImage",
                  commentsCount: 18,
                  rocketImage: "rocketImage",
                  rocketsCount: 43),
        PostModel(link: "https://www.tradingview.com/chart/EURUSD/5CC4klSD-EURUSD/",
                  postImage: "Post3",
                  title: "EURUSD",
                  subTitle: "Hello traders ,what do you think about EURUSD? This week, the spotlight is on the upcoming release of the Eurozone's Consumer Price Index data for December, scheduled for Wednesday, January 17.",
                  author: "HAMED_AZ",
                  commentImage: "commentImage",
                  commentsCount: 18,
                  rocketImage: "rocketImage",
                  rocketsCount: 150),
        PostModel(link: "https://www.tradingview.com/chart/EURUSD/ThVzIuG0-HelenP-I-Euro-can-little-correct-and-then-make-impulse-up/",
                  postImage: "Post4",
                  title: "HelenP. I Euro can little correct and then make impulse up",
                  subTitle: "Hi folks today I'm prepared for you Ripple analytics. Some time ago price declined to the 1.0830 support level, which coincided with the support zone, and at once rebounded and...",
                  author: "FirstNameHelen",
                  commentImage: "commentImage",
                  commentsCount: 4,
                  rocketImage: "rocketImage",
                  rocketsCount: 15),
        PostModel(link: "https://www.tradingview.com/chart/USDCAD/HSu2Mw5j-USDCAD-New-Year-2024-New-Outlook/",
                  postImage: "Post5",
                  title: "USDCAD: New Year 2024, New Outlook!",
                  subTitle: "Merry Christmas Everyone, Dear Traders, This week we waited USD to reverse and show some strong bullish momentum though it did not, however, this week we may see some bullish price movement.",
                  author: "Setupsfx_",
                  commentImage: "commentImage",
                  commentsCount: 6,
                  rocketImage: "rocketImage",
                  rocketsCount: 68),
        PostModel(link: "https://www.tradingview.com/chart/CHFJPY/7z4eTa3n-CHFJPY-forming-a-rising-wedge/",
                  postImage: "Post6",
                  title: "CHFJPY forming a rising wedge",
                  subTitle: "A rising wedge is taking shape in CHFJPY, accompanied by a noticeable divergence on the chart. There's a likelihood of a reversal in the upward trend.",
                  author: "hassanejaz1",
                  commentImage: "commentImage",
                  commentsCount: 4,
                  rocketImage: "rocketImage",
                  rocketsCount: 6),
        PostModel(link: "https://www.tradingview.com/chart/GBPUSD/l3UMC3Qe-GBPUSD-Update-1000-PIPS-Idea-is-Still-Valid/",
                  postImage: "Post7",
                  title: "#GBPUSD: Update 1000 PIPS Idea is Still Valid",
                  subTitle: "Dear Traders. Our last idea on FX:GBPUSD we had given you an important update that price will go slightly higher around 1.2760 and then reject from there and price did the exactly same thing.",
                  author: "Setupsfx_",
                  commentImage: "commentImage",
                  commentsCount: 8,
                  rocketImage: "rocketImage",
                  rocketsCount: 39),
        PostModel(link: "https://www.tradingview.com/chart/GBPUSD/VHE55kAq-Lingrid-GBPUSD-short-from-RANGE-zone/",
                  postImage: "Post8",
                  title: "Lingrid | GBPUSD short from RANGE zone",
                  subTitle: "The price perfectly fulfills my last idea. The price fell and hit the target level. FX:GBPUSD broke through the range and made a new lower low.",
                  author: "Lingrid",
                  commentImage: "commentImage",
                  commentsCount: 4,
                  rocketImage: "rocketImage",
                  rocketsCount: 20),
        PostModel(link: "https://www.tradingview.com/chart/GBPNZD/dXkGtNss-Buy-GBPNZD/",
                  postImage: "Post9",
                  title: "Buy GBPNZD",
                  subTitle: "The major resistance zone at 2.057-2.060 has been decisively breached, a level that has notably functioned as both support and resistance in the past ten instances.",
                  author: "Trad3WithFaraz",
                  commentImage: "commentImage",
                  commentsCount: 1,
                  rocketImage: "rocketImage",
                  rocketsCount: 15),
        PostModel(link: "https://www.tradingview.com/chart/GBPJPY/4AuD7lKI-GBP-JPY-LONG-FROM-SUPPORT/",
                  postImage: "Post10",
                  title: "✅GBP_JPY LONG FROM SUPPORT🚀",
                  subTitle: "✅GBP_JPY went down to Retest the horizontal Support of 184.400 from Where I think we will See a bullish rebound LONG🚀",
                  author: "ProSignalsFx",
                  commentImage: "commentImage",
                  commentsCount: 2,
                  rocketImage: "rocketImage",
                  rocketsCount: 21),
        PostModel(link: "https://www.tradingview.com/chart/EURUSD/8PKXId9J-eurusd/",
                  postImage: "Post11",
                  title: "eurusd",
                  subTitle: "eurusd has moved according to our predictions, now we are waiting for the price to go even lower to fill the leftout Daily Imbalance",
                  author: "BigBenCapitals",
                  commentImage: "commentImage",
                  commentsCount: 1,
                  rocketImage: "rocketImage",
                  rocketsCount: 12),
        PostModel(link: "https://www.tradingview.com/chart/EURUSD/oaUauW4O-3-of-the-Top-Trading-Strategies/",
                  postImage: "Post12",
                  title: "3 of the Top Trading Strategies",
                  subTitle: "Trading in the financial markets requires a blend of intuition, analysis, and well-tested strategies. This article delves into three of the top trading strategies...",
                  author: "FXOpen",
                  commentImage: "commentImage",
                  commentsCount: 2,
                  rocketImage: "rocketImage",
                  rocketsCount: 15),
        PostModel(link: "https://www.tradingview.com/chart/AUDUSD/Dl41ET4F-AUDUSD-LONG-BOUNCE-UP/",
                  postImage: "Post13",
                  title: "AUDUSD LONG BOUNCE UP",
                  subTitle: "price aproaching its 4 hr support. likely to see price bounce up from support area making new daily high. long trade preferred with slight down price.",
                  author: "Fx_Stuns",
                  commentImage: "commentImage",
                  commentsCount: 1,
                  rocketImage: "rocketImage",
                  rocketsCount: 14),
        PostModel(link: "https://www.tradingview.com/chart/GBPJPY/h9o3tej0-Why-I-think-GBPJPY-Will-Continue-to-Buy-This-Week/",
                  postImage: "Post14",
                  title: "Why I think GBPJPY Will Continue to Buy This Week",
                  subTitle: "Hey Rich Friends, This is only a technical analysis so make sure to check the news and any other indicators on your chart for additional confirmation.",
                  author: "MoneyMantraCha",
                  commentImage: "commentImage",
                  commentsCount: 5,
                  rocketImage: "rocketImage",
                  rocketsCount: 19),
        PostModel(link: "https://www.tradingview.com/chart/EURNZD/uKH1OHB2-Resistance-Zone-Ahead/",
                  postImage: "Post15",
                  title: "Resistance Zone Ahead",
                  subTitle: "The range between 1.77200 and 1.77370 is poised to be a crucial barometer for both bulls and bears. This level represents the Fibonacci 0.38 retracement from 1.82823 to 1.73843 and...",
                  author: "Trad3WithFaraz",
                  commentImage: "commentImage",
                  commentsCount: 2,
                  rocketImage: "rocketImage",
                  rocketsCount: 31),
        PostModel(link: "https://www.tradingview.com/chart/EURJPY/eXmpxNYK-EURJPY-BULLISH-MOVE/",
                  postImage: "Post16",
                  title: "EURJPY - BULLISH MOVE 🚀",
                  subTitle: "As We Talked in The Previous Analysis: The EURJPY Reached a Support Level (155.372 - 154.420) The Price Formed an Ascending Triangle Pattern. The Resistance Level is Broken.",
                  author: "Hsan_Benhmed",
                  commentImage: "commentImage",
                  commentsCount: 6,
                  rocketImage: "rocketImage",
                  rocketsCount: 10),
        PostModel(link: "https://www.tradingview.com/chart/EURNZD/L1mRcpkj-EURNZD-2-HR-Big-bullish-move-expected/",
                  postImage: "Post17",
                  title: "EURNZD: 2 HR Big bullish move expected!",
                  subTitle: "EURNZD in Wyckoff Method, we can confirm that price is in verge of big bullish move of 400 pips at least. If you look through the chart carefully, we have given reason for each move...",
                  author: "Setupsfx_",
                  commentImage: "commentImage",
                  commentsCount: 3,
                  rocketImage: "rocketImage",
                  rocketsCount: 66),
        PostModel(link: "https://www.tradingview.com/chart/EURUSD/suDmfOVN-EURUSD-4hrs-Sell-Trade-Target-Range-150-PIP/",
                  postImage: "Post18",
                  title: "EURUSD - 4hrs ( Sell Trade Target Range 150 PIP )",
                  subTitle: "💵Pair Name : EUR/USD. Time Frame : 4hrs Chart / Close. Scale Type : Large Scale",
                  author: "GoldenEngine",
                  commentImage: "commentImage",
                  commentsCount: 2,
                  rocketImage: "rocketImage",
                  rocketsCount: 11),
        PostModel(link: "https://www.tradingview.com/chart/AUDJPY/6iWItUYi-AUDJPY-LONG/",
                  postImage: "Post19",
                  title: "AUDJPY LONG",
                  subTitle: "We can consider going long on AUD/JPY today, following the typical H4 uptrend strategy when it encounters support. If there's a double bottom, we can open a long position.",
                  author: "zzzoain",
                  commentImage: "commentImage",
                  commentsCount: 2,
                  rocketImage: "rocketImage",
                  rocketsCount: 6),
        PostModel(link: "https://www.tradingview.com/chart/EURGBP/S32fWqWO-EURGBP-BEARISH-MOVE/",
                  postImage: "Post20",
                  title: "EURGBP - BEARISH MOVE 📉",
                  subTitle: "Hello Traders! On Friday 1 Dec 23, The EURGBP Broke The Support Level (0.86162 - 0.86260). This Support Level Becomes a New Resistance Level.",
                  author: "Hsan_Benhmed",
                  commentImage: "commentImage",
                  commentsCount: 5,
                  rocketImage: "rocketImage",
                  rocketsCount: 9)
    ]
}
